const addresses = [
  "New York, New York, USA",
  "Los Angeles, California, USA",
  "Chicago, Illinois, USA",
  "Houston, Texas, USA",
  "Phoenix, Arizona, USA",
  "Philadelphia, Pennsylvania, USA",
  "San Antonio, Texas, USA",
  "San Diego, California, USA",
  "Dallas, Texas, USA",
  "San Jose, California, USA",
  "Austin, Texas, USA",
  "Jacksonville, Florida, USA",
  "Fort Worth, Texas, USA",
  "Columbus, Ohio, USA",
  "Charlotte, North Carolina, USA",
  "Indianapolis, Indiana, USA",
  "San Francisco, California, USA",
  "Seattle, Washington, USA",
  "Denver, Colorado, USA",
  "Washington, District of Columbia, USA",
  "Boston, Massachusetts, USA",
  "El Paso, Texas, USA",
  "Nashville, Tennessee, USA",
  "Detroit, Michigan, USA",
  "Oklahoma City, Oklahoma, USA",
  "Portland, Oregon, USA",
  "Las Vegas, Nevada, USA",
  "Memphis, Tennessee, USA",
  "Louisville, Kentucky, USA",
  "Baltimore, Maryland, USA",
];

const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "Indianapolis",
  "San Francisco",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Nashville",
  "Detroit",
  "Oklahoma City",
  "Portland",
  "Las Vegas",
  "Memphis",
  "Louisville",
  "Baltimore",
];

const countries = [
  "USA",
  "Canada",
  "Mexico",
  "Brazil",
  "Argentina",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "China",
  "India",
  "Japan",
  "South Korea",
  "Australia",
  "New Zealand",
  "South Africa",
  "Nigeria",
  "Egypt",
  "Russia",
];

export { cities, addresses, countries };
